//Objeto math 

let resultado;

resultado = Math.PI;
resultado = Math.round(2.7);
resultado = Math.ceil(2.1); // cell siempre va a redondear hacia arriba 
resultado = Math.floor(2.9); //Floor siempre redondea hacia abajo
resultado = Math.sqrt(144) // es una raiz cuadrada 
resultado = Math.abs(-200); // es para sacar los numeros negativo a positivos
resultado =  Math.min(3, 5, 1, 8, 2, 10); // es para sacar el minimo de un numero 
resultado =  Math.max(3, 5, 1, 8, 2, 10); // es para sacar el maximo  de un numero 
resultado = Math.random()
resultado = Math.floor(Math.random() * 30); // codigo para sacar numeros random



console.log(resultado);